### ISSUE TITLE
LittleFS assertion error

### ISSUE THREAD

**Issue by daradib** [rickkas7/PublishQueueAsyncRK#8]
After publishing an event successfully to the cloud, one of my devices blinked red SOS 10 times:

 - Particle Boron running DeviceOS 2.0.1
 - PublishQueueAsyncRK 0.2.0 with PublishQueueAsyncPOSIX

Here is the call stack from a Particle Debugger (replaced absolute file paths):

    HAL_Delay_Microseconds@0x0004d3ec (deviceOS/hal/src/nRF52840/delay_hal.cpp:43)
    panic_@0x00066e86 (deviceOS/services/src/panic.c:95)
    lfs_cache_prog@0x00092290 (deviceOS/third_party/littlefs/littlefs/lfs.c:183)
    lfs_file_write@0x00092c42 (deviceOS/third_party/littlefs/littlefs/lfs.c:1699)
    _write@0x00053a72 (deviceOS/hal/src/nRF52840/posix/syscalls_posix.cpp:286)
    _write_r@0x000a8dfc (/_write_r.cdasm:10)
    PublishQueueAsyncPOSIX::writeBytes@0x000316a2 (PublishQueueAsyncRK/src/PublishQueueAsyncRK.h:1625)
    PublishQueueAsyncPOSIX::writeBytes@0x000316a2 (PublishQueueAsyncRK/src/PublishQueueAsyncRK.h:1620)
    PublishQueueAsyncFileSystem::discardOldEvent@0x00031814 (PublishQueueAsyncRK/src/PublishQueueAsyncRK.h:1199)
    PublishQueueAsyncBase::checkQueueState@0x0003730e (PublishQueueAsyncRK/src/PublishQueueAsyncRK.cpp:75)
    PublishQueueAsyncBase::checkQueueState@0x0003730e (PublishQueueAsyncRK/src/PublishQueueAsyncRK.cpp:47)
    std::function<void (PublishQueueAsyncBase&)>::operator()(PublishQueueAsyncBase&) const@0x000371b0 (gcc-arm/arm-none-eabi/include/c++/9.2.1/bits/std_function.h:683)
    PublishQueueAsyncBase::threadFunction@0x000371b0 (PublishQueueAsyncRK/src/PublishQueueAsyncRK.cpp:34)
    PublishQueueAsyncBase::threadFunctionStatic@0x000371bc (PublishQueueAsyncRK/src/PublishQueueAsyncRK.cpp:104)
    Thread::run@0x00032f24 (deviceOS/wiring/inc/spark_wiring_thread.h:211)
    ??@0x0009179c (Unknown Source:0)

Apparently after the event is published, `PublishQueueAsyncFileSystem::discardOldEvent` tries to write 8 bytes to LittleFS, but LittleFS raises an assertion error:

    // pcache must have been flushed, either by programming and
    // entire block or manually flushing the pcache
    LFS_ASSERT(pcache->block == 0xffffffff);

The value of `pcache.block` is instead a different value like 28 (`0x1c`).

After calling `publishQueue.clearEvents()` I am unable to reproduce, but I'm not sure how LittleFS became corrupted(?) in the first place, and how to ensure this never occurs again. Perhaps a DeviceOS bug or insufficient power supply.

**Comment by rickkas7** [comment]
I would recommend not using PublishQueueAsyncRK with the POSIX file system adapter. A much better option is to directly use the PublishQueuePosixRK library (https://github.com/rickkas7/PublishQueuePosixRK) which is a significantly simplified and more reliable way of storing events on the file system.
